PREFIX : <http://murtenannotation.local/ver1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT DISTINCT ?q2_sub_rvi (?q1_ling_appl_content AS ?removed_content) WHERE {
  BIND ( <http://www.researchspace.org/resource/man_made_object/79530dbc-f4fd-462e-b4bc-50f5b813010c/frame/c06bbc29-3995-4829-b248-91d805ae70b6> as ?murten_frame)

      FILTER NOT EXISTS { #find all query attributes that are not recognized on the sub frames of the Murten Panorama

      ?q1_sub_framing crm:P140_assigned_attribute_to ?murten_frame.
      ?q1_sub_framing crm:P141_assigned ?q1_sub_frame.
      ?q1_sub_framing a <http://murtenannotation.local/ver1/Framing>.

      ?q1_sub_vr crm:P140_assigned_attribute_to ?q1_sub_frame.
      ?q1_sub_vr crm:P141_assigned ?q2_sub_rvi.
      ?q1_sub_vr a <http://murtenannotation.local/ver1/Visual_Recognition>.
      }

      ?q1_appl_assg crm:P140_assigned_attribute_to ?q2_sub_rvi.
      ?q1_appl_assg crm:P141_assigned ?q1_ling_appl.
      ?q1_ling_appl crm:P72_has_language/skos:prefLabel "eng".
      ?q1_ling_appl crm:P190_has_symbolic_content ?q1_ling_appl_content.
      ?q1_appl_assg a <http://murtenannotation.local/ver1/Appellation_Assignment>.

{
SELECT DISTINCT ?q2_sub_rvi WHERE { #select all the sub frame recognized visualitem (attributes) from the query frames => query attributes
  BIND ( <http://www.researchspace.org/resource/recognized_visual_item/adc8e1a7-aea3-4542-ad36-36bc80449320> as ?q2_rvi) #query recognized visualitem i.e. "Traveling women who identify themselves as such are spared."
  BIND ( <http://www.researchspace.org/resource/man_made_object/79530dbc-f4fd-462e-b4bc-50f5b813010c/frame/c06bbc29-3995-4829-b248-91d805ae70b6> as ?murten_frame)
      ?q2_vr crm:P141_assigned ?q2_rvi .
      ?q2_vr crm:P140_assigned_attribute_to ?q2_frame.
      ?q2_vr a <http://murtenannotation.local/ver1/Visual_Recognition>.

      ?q2_sub_framing crm:P140_assigned_attribute_to ?q2_frame.
      ?q2_sub_framing crm:P141_assigned ?q2_sub_frame.
      ?q2_sub_framing a <http://murtenannotation.local/ver1/Framing>.

      ?q2_sub_vr crm:P140_assigned_attribute_to ?q2_sub_frame.
      ?q2_sub_vr crm:P141_assigned ?q2_sub_rvi.
      ?q2_sub_vr a <http://murtenannotation.local/ver1/Visual_Recognition>.

FILTER (?q2_frame != ?murten_frame) #exclude the frame from the Murten Panorama from query frames
}
}


}